name: ddd
description: A learn project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.9.1
  freezed_annotation: ^0.7.1
  cupertino_icons: ^0.1.3
  flutter_bloc: ^4.0.0

dev_dependencies:
  build_runner:
  freezed: ^0.10.8

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
